version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: yarn
      - run:
          name: Build Packages
          command: yarn build
      - run:
          name: Verify Artifacts
          command: yarn test
